/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.wc;

import org.junit.Test;

import java.io.File;

import static org.junit.Assert.*;

public class AppTest {
    public void appHasAGreeting() {

    }
}
