/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.wc;

import java.io.File;

public class App {


    public static void main(String[] args) {
        try {
            File file = new File(args[0]);
            System.out.println(file.length());
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
}
